// Generated by Finicky Kickstart
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Browserosaurus",
  rewrite: [
    {
      // Redirect all urls to use https
      match: ({ url }) => url.protocol === "http",
      url: { protocol: "https" },
    },
    {
      // remove all marketing/tracking info from urls
      match: () => true, // Execute rewrite on all incoming urls to make this example easier to understand
      url: ({ url }) => {
        const removeKeysStartingWith = ["utm_", "uta_"]; // Remove all query parameters beginning with these strings
        const removeKeys = ["fbclid", "gclid"]; // Remove all query parameters matching these keys

        const search = url.search
          .split("&")
          .map((parameter) => parameter.split("="))
          .filter(
            ([key]) =>
              !removeKeysStartingWith.some((startingWith) =>
                key.startsWith(startingWith)
              )
          )
          .filter(
            ([key]) => !removeKeys.some((removeKey) => key === removeKey)
          );

        return {
          ...url,
          search: search.map((parameter) => parameter.join("=")).join("&"),
        };
      },
    },
  ],
  handlers: [
    {
      match: /^https?:\/\/.*exponea.*$/,
      browser: "Google Chrome",
    },
    {
      match: ({ opener }) => ["Twingate", "Slack"].includes(opener.name),
      browser: "Google Chrome",
    },
    {
      match: ({ opener }) => ["Discord", "Telegram"].includes(opener.name),
      browser: "Arc",
    },
    {
      match: /^https?:\/\/.*bloomreach.*$/,
      browser: "Google Chrome",
    },
    {
      match: "https://discord.com/*",
      url: { protocol: "discord" },
      browser: "Discord",
    },
    {
      match: "https://www.figma.com/file/*",
      browser: "Figma",
    },
    {
      match: finicky.matchDomains("open.spotify.com"),
      browser: "Spotify",
    },
  ],
};
