// Generated by Finicky Kickstart
// Save as ~/.finicky.js

const browsers = {
	personal: {
		name: "Arc",
		openInBackground: false,
	},
	work: {
		name: "Google Chrome",
		openInBackground: false,
	},
	selector: {
		name: "Browserino",
		openInBackground: false,
	},
	discord: {
		name: "Discord",
		openInBackground: false,
	},
	figma: {
		name: "Figma",
		openInBackground: false,
	},
	spotify: {
		name: "Spotify",
		openInBackground: false,
	},
};

export default {
	defaultBrowser: browsers.selector,
	options: {
		logRequests: false,
	},
	rewrite: [
		{
			match: () => true,
			url: (url) => {
				const removeKeysStartingWith = ["utm_", "uta_"];
				const removeKeys = ["fbclid", "gclid"];
				for (const key of [...url.searchParams.keys()]) {
					if (removeKeysStartingWith.some((prefix) => key.startsWith(prefix)) || removeKeys.includes(key)) {
						url.searchParams.delete(key);
					}
				}
				return url;
			},
		},
		{
			match: (url) => url.host === "discord.com",
			url: (url) => {
				url.protocol = "discord:";
				return url;
			},
		},
	],
	handlers: [
		{
			match: (_url, { opener }) => opener !== null && ["Slack", "Netbird"].includes(opener.name),
			browser: browsers.work,
		},
		{
			match: (_url, { opener }) => opener !== null && ["Airmail"].includes(opener.name),
			browser: browsers.selector,
		},
		{
			match: (_url, { opener }) => opener !== null && ["Discord", "Telegram"].includes(opener.name),
			browser: browsers.personal,
		},
		{
			match: /^https?:\/\/.*omnetic.*$/,
			browser: browsers.work,
		},
		{
			match: /^https?:\/\/carvago\.atlassian\.net\/.*$/,
			browser: browsers.work,
		},
		{
			match: (url) => url.protocol === "discord:",
			browser: browsers.discord,
		},
		{
			match: "https://www.figma.com/file/*",
			browser: browsers.figma,
		},
		{
			match: finicky.matchHostnames("open.spotify.com"),
			browser: browsers.spotify,
		},
	],
};
