// Generated by Finicky Kickstart
// Save as ~/.finicky.js

const browsers = {
	personal: {
		name: "Arc",
		openInBackground: false,
	},
	work: {
		name: "Google Chrome",
		openInBackground: false,
	},
	selector: {
		name: "Browserino",
		openInBackground: false,
	},
	discord: {
		name: "Discord",
		openInBackground: false,
	},
	figma: {
		name: "Figma",
		openInBackground: false,
	},
	spotify: {
		name: "Spotify",
		openInBackground: false,
	},
};

export default {
	defaultBrowser: browsers.selector,
	options: {
		logRequests: false,
	},
	rewrite: [
		{
			match: () => true, // Execute rewrite on all incoming urls to make this example easier to understand
			url: ({ url }) => {
				const removeKeysStartingWith = ["utm_", "uta_"]; // Remove all query parameters beginning with these strings
				const removeKeys = ["fbclid", "gclid"]; // Remove all query parameters matching these keys

				const search = url.search
					.split("&")
					.map((parameter) => parameter.split("="))
					.filter(([key]) => !removeKeysStartingWith.some((startingWith) => key.startsWith(startingWith)))
					.filter(([key]) => !removeKeys.some((removeKey) => key === removeKey));

				return {
					...url,
					search: search.map((parameter) => parameter.join("=")).join("&"),
				};
			},
		},
	],
	handlers: [
		{
			match: ({ opener }) => ["Slack", "Netbird"].includes(opener.name),
			browser: browsers.work,
		},
		{
			match: ({ opener }) => ["Airmail"].includes(opener.name),
			browser: browsers.selector,
		},
		{
			match: ({ opener }) => ["Discord", "Telegram"].includes(opener.name),
			browser: browsers.personal,
		},
		{
			match: /^https?:\/\/.*omnetic.*$/,
			browser: browsers.work,
		},
		{
			match: "https://discord.com/*",
			url: { protocol: "discord" },
			browser: browsers.discord,
		},
		{
			match: "https://www.figma.com/file/*",
			browser: browsers.figma,
		},
		{
			match: finicky.matchHostnames("open.spotify.com"),
			browser: browsers.spotify,
		},
	],
};
